### ISSUE TITLE
Add setParam to ApplicationInterface

### ISSUE THREAD

**Issue by omsi668** [objective-php/application#24]
Hello,

We have to do a $app->setParam when we are in a renderable action.

In this case $app is an ApplicationInterface. It works because the object implements it, but the interface doesn't.

Please add public function setParam($param, $value) to ObjectivePHP\Application\ApplicationInterface for coherence

Thank you,

**Comment by rflavien** [comment]
Hi @omsi668 

Can you explain more your need please. I'm not sure that in all, and every, case a renderable action will need this call.

My first clue, is that you can use `getConfig()` from `ObjectivePHP\Application\ApplicationInterface` to import a param with an `ApplicationInterface`.

**Comment by omsi668** [comment]
Typically to set the layout.name for example we seems to need that (it took that behavior from applications made by opcoding).
$app->setParam('layout.name', false);

Then the autocomplete is broken.

I'll let you see if this issue is relevant

**Comment by rflavien** [comment]
Ok thanks for the exemple, I understand better :)

I think this will not be add because changing the interface can introduce BC break.

We already planned to break things in the under development ApplicationInterface v2, and this kind of needs will be managed in another way.
