### ISSUE TITLE
Headers already sent by

### ISSUE THREAD

**Issue by omsi668** [objective-php/application#6]
Hello, 

The Objective framework is catching an unknown error on my project then creates an error "Headers already sent by"

When commenting line 32 of src/Operation/ExceptionHandler (the throw), everything works just fine.

Initial error looks like an Exception raised by homemade classes, when there is no Exception, everything works fine.

Thank you

**Comment by Neofox** [comment]
Exemple of backtrace:

Fatal error: Uncaught RuntimeException: Unable to emit response; headers already sent in /var/www/customerportal/builds/1484649019/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php:31 
Stack trace: 
#0 /var/www/customerportal/builds/1484649019/vendor/objective-php/application/src/Operation/ExceptionHandler.php(95): Zend\Diactoros\Response\SapiEmitter->emit(Object(Zend\Diactoros\Response\HtmlResponse)) 
#1 /var/www/customerportal/builds/1484649019/vendor/objective-php/invokable/src/Invokable.php(62): ObjectivePHP\Application\Operation\ExceptionHandler->__invoke(Object(Application)) 
#2 /var/www/customerportal/builds/1484649019/vendor/objective-php/invokable/src/AbstractInvokable.php(31): ObjectivePHP\Invokable\Invokable->run(Object(Application)) 
#3 /var/www/customerportal/builds/1484649019/vendor/objective-php/application/src/AbstractApplication.php(361): ObjectivePHP\Invokable\AbstractInvokable->__invoke(Object(Application)) 
#4 /var/www/customerportal/builds/1484649019/public/index.php(15): ObjectivePHP\Applica in /var/www/customerportal/builds/1484649019/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php on line 31

**Comment by Neofox** [comment]
Pourrais je avoir un follow up ?

Merci

**Comment by gauthier** [comment]
Salut Jérôme,

j'avoue que je n'ai pas réussi à reproduire ce problème. Il semblerait que ce soit un effet de bord du à une exception lancée par le SapiEmitter, catchée par l'ExceptionHandler, puis à nouveau transmise au SapiEmitter. Si tu sais me donner un protocole pour reproduire, ça m'aiderait beaucoup !

**Comment by glickel** [comment]
Hi, I have a solution for you if you want :)
[https://github.com/objective-php/application/pull/18](url)
The problem is in ExceptionHandler, you use SapiEmitter with a not empty output buffer.
