### ISSUE TITLE
Exception not shown fully

### ISSUE THREAD

**Issue by fmagyari** [objective-php/application#8]
Hi Objective-php team,

Regarding the "Stack trace" when we have an Error Exception, if the line of the error reporting is too long, we don't have the full issue sentence ( ended with '...' ).
Is it possible to have the full Error message ?

Thanks

**Comment by gauthier** [comment]
Hi Flo,

can you please provide us with the version of the package you are actually using (`composer show | grep objective-php/application`) and also a full output of the ErrorHandler if you can reproduce the issue.

Thanks ;)
